# Generated by Django 5.2.5 on 2025-08-15 15:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import home.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_blogpage_policy"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "pets",
                    wagtail.fields.StreamField(
                        [("cat", 11), ("dog", 11)],
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.URLBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageBlock", [], {}),
                            3: (
                                "wagtail.blocks.StreamBlock",
                                [[("text", 0), ("link", 1), ("image", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.CharBlock", (), {}),
                            5: ("wagtail.blocks.DateBlock", (), {}),
                            6: ("wagtail.blocks.TimeBlock", (), {}),
                            7: ("wagtail.blocks.IntegerBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("time", 6), ("portions", 7), ("food", 4)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": home.blocks.get_colour_choices},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("story", 3),
                                        ("name", 4),
                                        ("date_of_birth", 5),
                                        ("feeding_schedule", 9),
                                        ("colour", 10),
                                        ("picture", 2),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
